yellowjackets = ['jackie', 'shauna', 'taissa', 'van', 'nat', 'lottie', 'laura_lee', 'melissa', 'akilah', 'mari', 'gen', 'crystal', 'robin', 'britt']
print(f"{yellowjackets[0].title()} makes the first meal")
print(f"{yellowjackets[1].title()} takes the first bite")
print(yellowjackets[2].title())
print(yellowjackets[3].title())
print(yellowjackets[4].title())
print(yellowjackets[5].title())
print(yellowjackets[6].title())
print(yellowjackets[7].title())
print(yellowjackets[8].title())
print(yellowjackets[9].title())
print(yellowjackets[11].title())
print(yellowjackets[13].title())
print("All copy Shauna")